apiVersion: v1
kind: Service
metadata:
  name: frontend-service  # 서비스 이름
spec:
  selector:
    app: portfolio        # deployment.yaml의 Pod 라벨(app: portfolio)과 일치시킴
  ports:
    - protocol: TCP
      port: 80            # 서비스 내부 포트
      targetPort: 80      # 컨테이너(Nginx) 내부 포트
      nodePort: 30080     # 외부에서 접속할 포트 (30000~32767 사이)
  type: NodePort          # 로컬 환경에서 가장 확실한 연결 방식
