server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # 모든 요청을 index.html로 보내 React Router가 처리하게 함
        try_files $uri $uri/ /index.html;
    }
}